<?php

define("DATABASE_SERVER", "INSERT_SERVER_HERE");
define("DATABASE_USERNAME", "INSERT_USERNAME_HERE");
define("DATABASE_DEFAULT_DB", "INSERT_DEFAULT_DB_HERE");
define("DATABASE_PASSWORD", "INSERT_PASSWORD_HERE");

?>